shortlinks:
  discord: discord-alert.sh   # Custom Shortlinks!
  smtp: discord-alert.sh

excludeScripts:
  - smtp                      # Excludes Shortlink from being counted
  - discord.sh                # Excludes the root file from being counted
