shortlinks:
  discord: discord-alert.sh   # Custom Shortlinks!
  smtp: smtp-send-logs.sh

excludeScripts:
  - smtp                      # Excludes Shortlink from being counted
  - discord-alert.sh          # Excludes the root file from being counted
